<?php
return array(
    'Auction\\V1\\Rest\\Auction\\Controller' => array(
        'collection' => array(
            'GET' => array(
                'response' => '{
   "_links": {
       "self": {
           "href": "/auction"
       },
       "first": {
           "href": "/auction?page={page}"
       },
       "prev": {
           "href": "/auction?page={page}"
       },
       "next": {
           "href": "/auction?page={page}"
       },
       "last": {
           "href": "/auction?page={page}"
       }
   }
   "_embedded": {
       "auction": [
           {
               "_links": {
                   "self": {
                       "href": "/auction[/:auction_id]"
                   }
               }
              "auction_id": "",
              "user_id": "",
              "auction_start_unixtime": "",
              "auction_end_unixtime": "",
              "auction_min_bid_value": "",
              "auction_current_bid_value": "",
              "auction_num_bids": "",
              "auction_heading": "",
              "auction_subtitle": "",
              "auction_featured_flag": "",
              "auction_reserve_flag": "",
              "auction_reserve_value": "",
              "auction_discount": "",
              "auction_item_qty": "",
              "auction_item_qty_left": "",
              "auction_secure_flag": "",
              "auction_auto_relist_flag": "",
              "auction_end_early_flag": "",
              "auction_end_early_value": "",
              "auction_status": "",
              "auction_desc_memo": "",
              "auction_shipping_memo": "",
              "auction_type": "",
              "auction_location_zip_code": "",
              "auction_location_city": "",
              "auction_location_state": "",
              "auction_offsite_flag": "",
              "auction_user_hidden_flag": "",
              "auction_relist_count": "",
              "auction_view_count": "",
              "auction_days": "",
              "dirty_flag": "",
              "last_modified": "",
              "auction_hours": "",
              "auction_source": "",
              "auction_priority": "",
              "last_modified_by": "",
              "creator_id": ""
           }
       ]
   }
}',
            ),
            'POST' => array(
                'request' => '{
   "auction_id": "",
   "user_id": "",
   "auction_start_unixtime": "",
   "auction_end_unixtime": "",
   "auction_min_bid_value": "",
   "auction_current_bid_value": "",
   "auction_num_bids": "",
   "auction_heading": "",
   "auction_subtitle": "",
   "auction_featured_flag": "",
   "auction_reserve_flag": "",
   "auction_reserve_value": "",
   "auction_discount": "",
   "auction_item_qty": "",
   "auction_item_qty_left": "",
   "auction_secure_flag": "",
   "auction_auto_relist_flag": "",
   "auction_end_early_flag": "",
   "auction_end_early_value": "",
   "auction_status": "",
   "auction_desc_memo": "",
   "auction_shipping_memo": "",
   "auction_type": "",
   "auction_location_zip_code": "",
   "auction_location_city": "",
   "auction_location_state": "",
   "auction_offsite_flag": "",
   "auction_user_hidden_flag": "",
   "auction_relist_count": "",
   "auction_view_count": "",
   "auction_days": "",
   "dirty_flag": "",
   "last_modified": "",
   "auction_hours": "",
   "auction_source": "",
   "auction_priority": "",
   "last_modified_by": "",
   "creator_id": ""
}',
                'response' => '{
   "_links": {
       "self": {
           "href": "/auction[/:auction_id]"
       }
   }
   "auction_id": "",
   "user_id": "",
   "auction_start_unixtime": "",
   "auction_end_unixtime": "",
   "auction_min_bid_value": "",
   "auction_current_bid_value": "",
   "auction_num_bids": "",
   "auction_heading": "",
   "auction_subtitle": "",
   "auction_featured_flag": "",
   "auction_reserve_flag": "",
   "auction_reserve_value": "",
   "auction_discount": "",
   "auction_item_qty": "",
   "auction_item_qty_left": "",
   "auction_secure_flag": "",
   "auction_auto_relist_flag": "",
   "auction_end_early_flag": "",
   "auction_end_early_value": "",
   "auction_status": "",
   "auction_desc_memo": "",
   "auction_shipping_memo": "",
   "auction_type": "",
   "auction_location_zip_code": "",
   "auction_location_city": "",
   "auction_location_state": "",
   "auction_offsite_flag": "",
   "auction_user_hidden_flag": "",
   "auction_relist_count": "",
   "auction_view_count": "",
   "auction_days": "",
   "dirty_flag": "",
   "last_modified": "",
   "auction_hours": "",
   "auction_source": "",
   "auction_priority": "",
   "last_modified_by": "",
   "creator_id": ""
}',
            ),
        ),
        'entity' => array(
            'GET' => array(
                'response' => '{
   "_links": {
       "self": {
           "href": "/auction[/:auction_id]"
       }
   }
   "auction_id": "",
   "user_id": "",
   "auction_start_unixtime": "",
   "auction_end_unixtime": "",
   "auction_min_bid_value": "",
   "auction_current_bid_value": "",
   "auction_num_bids": "",
   "auction_heading": "",
   "auction_subtitle": "",
   "auction_featured_flag": "",
   "auction_reserve_flag": "",
   "auction_reserve_value": "",
   "auction_discount": "",
   "auction_item_qty": "",
   "auction_item_qty_left": "",
   "auction_secure_flag": "",
   "auction_auto_relist_flag": "",
   "auction_end_early_flag": "",
   "auction_end_early_value": "",
   "auction_status": "",
   "auction_desc_memo": "",
   "auction_shipping_memo": "",
   "auction_type": "",
   "auction_location_zip_code": "",
   "auction_location_city": "",
   "auction_location_state": "",
   "auction_offsite_flag": "",
   "auction_user_hidden_flag": "",
   "auction_relist_count": "",
   "auction_view_count": "",
   "auction_days": "",
   "dirty_flag": "",
   "last_modified": "",
   "auction_hours": "",
   "auction_source": "",
   "auction_priority": "",
   "last_modified_by": "",
   "creator_id": ""
}',
            ),
            'PATCH' => array(
                'request' => '{
   "auction_id": "",
   "user_id": "",
   "auction_start_unixtime": "",
   "auction_end_unixtime": "",
   "auction_min_bid_value": "",
   "auction_current_bid_value": "",
   "auction_num_bids": "",
   "auction_heading": "",
   "auction_subtitle": "",
   "auction_featured_flag": "",
   "auction_reserve_flag": "",
   "auction_reserve_value": "",
   "auction_discount": "",
   "auction_item_qty": "",
   "auction_item_qty_left": "",
   "auction_secure_flag": "",
   "auction_auto_relist_flag": "",
   "auction_end_early_flag": "",
   "auction_end_early_value": "",
   "auction_status": "",
   "auction_desc_memo": "",
   "auction_shipping_memo": "",
   "auction_type": "",
   "auction_location_zip_code": "",
   "auction_location_city": "",
   "auction_location_state": "",
   "auction_offsite_flag": "",
   "auction_user_hidden_flag": "",
   "auction_relist_count": "",
   "auction_view_count": "",
   "auction_days": "",
   "dirty_flag": "",
   "last_modified": "",
   "auction_hours": "",
   "auction_source": "",
   "auction_priority": "",
   "last_modified_by": "",
   "creator_id": ""
}',
                'response' => '{
   "_links": {
       "self": {
           "href": "/auction[/:auction_id]"
       }
   }
   "auction_id": "",
   "user_id": "",
   "auction_start_unixtime": "",
   "auction_end_unixtime": "",
   "auction_min_bid_value": "",
   "auction_current_bid_value": "",
   "auction_num_bids": "",
   "auction_heading": "",
   "auction_subtitle": "",
   "auction_featured_flag": "",
   "auction_reserve_flag": "",
   "auction_reserve_value": "",
   "auction_discount": "",
   "auction_item_qty": "",
   "auction_item_qty_left": "",
   "auction_secure_flag": "",
   "auction_auto_relist_flag": "",
   "auction_end_early_flag": "",
   "auction_end_early_value": "",
   "auction_status": "",
   "auction_desc_memo": "",
   "auction_shipping_memo": "",
   "auction_type": "",
   "auction_location_zip_code": "",
   "auction_location_city": "",
   "auction_location_state": "",
   "auction_offsite_flag": "",
   "auction_user_hidden_flag": "",
   "auction_relist_count": "",
   "auction_view_count": "",
   "auction_days": "",
   "dirty_flag": "",
   "last_modified": "",
   "auction_hours": "",
   "auction_source": "",
   "auction_priority": "",
   "last_modified_by": "",
   "creator_id": ""
}',
            ),
            'PUT' => array(
                'request' => '{
   "auction_id": "",
   "user_id": "",
   "auction_start_unixtime": "",
   "auction_end_unixtime": "",
   "auction_min_bid_value": "",
   "auction_current_bid_value": "",
   "auction_num_bids": "",
   "auction_heading": "",
   "auction_subtitle": "",
   "auction_featured_flag": "",
   "auction_reserve_flag": "",
   "auction_reserve_value": "",
   "auction_discount": "",
   "auction_item_qty": "",
   "auction_item_qty_left": "",
   "auction_secure_flag": "",
   "auction_auto_relist_flag": "",
   "auction_end_early_flag": "",
   "auction_end_early_value": "",
   "auction_status": "",
   "auction_desc_memo": "",
   "auction_shipping_memo": "",
   "auction_type": "",
   "auction_location_zip_code": "",
   "auction_location_city": "",
   "auction_location_state": "",
   "auction_offsite_flag": "",
   "auction_user_hidden_flag": "",
   "auction_relist_count": "",
   "auction_view_count": "",
   "auction_days": "",
   "dirty_flag": "",
   "last_modified": "",
   "auction_hours": "",
   "auction_source": "",
   "auction_priority": "",
   "last_modified_by": "",
   "creator_id": ""
}',
                'response' => '{
   "_links": {
       "self": {
           "href": "/auction[/:auction_id]"
       }
   }
   "auction_id": "",
   "user_id": "",
   "auction_start_unixtime": "",
   "auction_end_unixtime": "",
   "auction_min_bid_value": "",
   "auction_current_bid_value": "",
   "auction_num_bids": "",
   "auction_heading": "",
   "auction_subtitle": "",
   "auction_featured_flag": "",
   "auction_reserve_flag": "",
   "auction_reserve_value": "",
   "auction_discount": "",
   "auction_item_qty": "",
   "auction_item_qty_left": "",
   "auction_secure_flag": "",
   "auction_auto_relist_flag": "",
   "auction_end_early_flag": "",
   "auction_end_early_value": "",
   "auction_status": "",
   "auction_desc_memo": "",
   "auction_shipping_memo": "",
   "auction_type": "",
   "auction_location_zip_code": "",
   "auction_location_city": "",
   "auction_location_state": "",
   "auction_offsite_flag": "",
   "auction_user_hidden_flag": "",
   "auction_relist_count": "",
   "auction_view_count": "",
   "auction_days": "",
   "dirty_flag": "",
   "last_modified": "",
   "auction_hours": "",
   "auction_source": "",
   "auction_priority": "",
   "last_modified_by": "",
   "creator_id": ""
}',
            ),
            'DELETE' => array(
                'request' => '{
   "auction_id": "",
   "user_id": "",
   "auction_start_unixtime": "",
   "auction_end_unixtime": "",
   "auction_min_bid_value": "",
   "auction_current_bid_value": "",
   "auction_num_bids": "",
   "auction_heading": "",
   "auction_subtitle": "",
   "auction_featured_flag": "",
   "auction_reserve_flag": "",
   "auction_reserve_value": "",
   "auction_discount": "",
   "auction_item_qty": "",
   "auction_item_qty_left": "",
   "auction_secure_flag": "",
   "auction_auto_relist_flag": "",
   "auction_end_early_flag": "",
   "auction_end_early_value": "",
   "auction_status": "",
   "auction_desc_memo": "",
   "auction_shipping_memo": "",
   "auction_type": "",
   "auction_location_zip_code": "",
   "auction_location_city": "",
   "auction_location_state": "",
   "auction_offsite_flag": "",
   "auction_user_hidden_flag": "",
   "auction_relist_count": "",
   "auction_view_count": "",
   "auction_days": "",
   "dirty_flag": "",
   "last_modified": "",
   "auction_hours": "",
   "auction_source": "",
   "auction_priority": "",
   "last_modified_by": "",
   "creator_id": ""
}',
                'response' => '{
   "_links": {
       "self": {
           "href": "/auction[/:auction_id]"
       }
   }
   "auction_id": "",
   "user_id": "",
   "auction_start_unixtime": "",
   "auction_end_unixtime": "",
   "auction_min_bid_value": "",
   "auction_current_bid_value": "",
   "auction_num_bids": "",
   "auction_heading": "",
   "auction_subtitle": "",
   "auction_featured_flag": "",
   "auction_reserve_flag": "",
   "auction_reserve_value": "",
   "auction_discount": "",
   "auction_item_qty": "",
   "auction_item_qty_left": "",
   "auction_secure_flag": "",
   "auction_auto_relist_flag": "",
   "auction_end_early_flag": "",
   "auction_end_early_value": "",
   "auction_status": "",
   "auction_desc_memo": "",
   "auction_shipping_memo": "",
   "auction_type": "",
   "auction_location_zip_code": "",
   "auction_location_city": "",
   "auction_location_state": "",
   "auction_offsite_flag": "",
   "auction_user_hidden_flag": "",
   "auction_relist_count": "",
   "auction_view_count": "",
   "auction_days": "",
   "dirty_flag": "",
   "last_modified": "",
   "auction_hours": "",
   "auction_source": "",
   "auction_priority": "",
   "last_modified_by": "",
   "creator_id": ""
}',
            ),
        ),
    ),
);
